basePath: /SFLeads/
consumes:
  - application/json
definitions:
  lead:
    additionalProperties: false
    description: ''
    properties:
      comments:
        type: string
      company:
        type: string
      email:
        type: string
      fname:
        type: string
      id:
        type: string
      lname:
        type: string
      phone:
        type: string
    type: object
info:
  title: SFLeads
  version: 0.0.1
paths:
  /lead:
    post:
      operationId: lead.create
      parameters:
        - description: Model instance data
          in: body
          name: data
          required: true
          schema:
            $ref: '#/definitions/lead'
      responses:
        '201':
          description: Request was successful
          schema:
            $ref: '#/definitions/lead'
      summary: Create a new instance of the model and persist it into the data source.
      tags:
        - lead
  /lead/{id}:
    get:
      operationId: lead.findById
      parameters:
        - description: lead id
          in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/lead'
      summary: Find a model instance by {{id}} from the data source.
      tags:
        - lead
produces:
  - application/json
schemes:
  - http
swagger: '2.0'
host: jgr-designer-sfleads-http-tools.apps.67ba7eaa5cdc1e00e52b26c6.ap1.techzone.ibm.com
